### ISSUE TITLE
2 things

### ISSUE THREAD

**Issue by ignhedgy** [degeneratehyperbola/NEPS#10]
Hi, it's me again. On my last suggestion I spoke about how antiaim didn't work well, it was because the cpp file was damaged. Now it's fixed. (idk why that happaned)
First thing: I don't know if this is because of some "fix" that doesnt work, but my playermodel keeps sliding serverside, even tho i don't have antiaim enabled. I tried screwing around with some of the settings in the "misc" tab with no success (I also have moonwalk unchecked). I haven't figured out a solution for it so far, if you do, please let me know.

Second thing: Last time we spoke about the resolver only having about 33% chance of resolving the head, this time I have a feature request. I don't know if this has been added (or I'm just blind lmao) but could you add an autostop to the aimbot tab? It would make a shit ton of difference in hvh.

**Comment by degeneratehyperbola** [comment]
You aren't blind, there is no auto-stop, yet... It is a good idea though, and definitely will be implemented at some point.
As for sliding, I don't and, probably, won't know what is going on with it, until I will be able to reproduce such behaviour. For now try  either recompiling (VS Build likes to screw up simple things like inlining :) ) or using the pre-built release https://github.com/degeneratehyperbola/NEPS/releases/latest

**Comment by degeneratehyperbola** [comment]
Added auto-stop in 75711a826d284e8d558c558b8e2582ac4e93e3f1
