### ISSUE TITLE
my discord or my github

### ISSUE THREAD

**Issue by tazetheKing** [degeneratehyperbola/NEPS#107]
hi i don't find the thing. i want to change that: my discord or my github. is there a thing and if you gonna click it he gonna send you to his sv. how do i change>?

**Comment by degeneratehyperbola** [comment]
Unfortunately for You, it is against the ![license](https://github.com/degeneratehyperbola/NEPS/blob/master/LICENSE.md) to change that part of the code, so I can't guide You on how to modify it
