### ISSUE TITLE
No-Recoil

### ISSUE THREAD

**Issue by XylylWoofer** [degeneratehyperbola/NEPS#11]
**Is your feature request related to a problem? Please describe.**
Aimbot is too inaccurate for raging due to there being no recoil reduction/removal.

**Describe the solution you'd like**
Add No-Recoil

**Describe alternatives you've considered**
N/A

**Comment by degeneratehyperbola** [comment]
By default aimbot accounts for recoil always, whether you rage or not, although there is no standalone recoil control yet.

**Comment by XylylWoofer** [comment]
> By default aimbot accounts for recoil always, whether you rage or not, although there is no standalone recoil control yet.

I could tell it accounted but didn't try and control it.

**Comment by 0zl** [comment]
+1. Bring back old RCS Features for aimbot

**Comment by ThebestkillerTBK** [comment]
I have implemented it in #72

**Comment by degeneratehyperbola** [comment]
Added in 4835aa0941ae5d89985bb0d904dae3d2f9f3c9ec
