### ISSUE TITLE
NEPS gets vac error on casual servers causing you to be kicked until you restart steam

### ISSUE THREAD

**Issue by ConnorBP** [degeneratehyperbola/NEPS#110]
**Describe the bug**
sv_pure bypass gets you kicked from casual servers.

**To Reproduce**
1. have sv_pure bypass on
2. play casual
3. play for a while
4. eventually get kicked out with the vac error "something is blocking the vac system or files are modified blah blah"

**Expected behavior**
the bypass should not cause you to get kicked from a game........

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://i.imgur.com/x30hFEu.png)

**Desktop (please complete the following information):**
 - latest github commit as of this report [fc08661](https://github.com/degeneratehyperbola/NEPS/commit/fc086610ea7e5947aeb135d2191aabfba2e47676)

**Additional context**
I have tested by having sv_pure disabled while playing on casual for a couple hours and then when i have it on after about an hour it will kick you, probably less. Not sure if someone reporting you in game causes some kind of scan that the bypass blocks causing the error or what it is, but its annoying af none the less. This error never happens on default osiris either. I'm 90% sure its related to the sv_pure bypass but who knows maybe it is something else that is different between default osiris and neps.

**Comment by ThebestkillerTBK** [comment]
Use VAC bypass tools and your image is fake

**Comment by ConnorBP** [comment]
> Use VAC bypass tools

its not an issue of vac bypass. I use a vac bypass. And on anything but NEPS or OsirisAndExtra by notgoodusername which have the same bypass it is fine. The bypass is on by default, and the way it works is not liked by casual for whatever reason. This issue does not happen if you disable the sv pure bypass, but the fact that it is on by default is quite the annoyance until you find out it was the cause.

**Comment by mcoo** [comment]
![image](https://user-images.githubusercontent.com/26184088/160277240-376d0801-6378-44d9-8df2-45e7909e238a.png)
me too

**Comment by notgoodusename** [comment]
Didnt even know this happened, are you using migi? and if so are you using the last version?

**Comment by SteakySteaks** [comment]
change your aimstep settings dum dum

**Comment by degeneratehyperbola** [comment]
Aimstep is kinda broken right now, but yes it is made exactly for this
