### ISSUE TITLE
Separate configs for skin changer

### ISSUE THREAD

**Issue by Minecraft-Kid** [degeneratehyperbola/NEPS#121]
**Is your feature request related to a problem? Please describe.**
No. It's just a thing that I would like

**Describe the solution you'd like**
A separate config for the skin changer, I don't like flooding my config tab with 20 copies of the same config with different skins, and I'm sure other people don't like either, so a new config space in the skin changer tab would be good, so you can use the same skins in different configs and different skins in the same config.

**Comment by degeneratehyperbola** [comment]
There is already a thing called "incremental load", you load any config normally and then, incrementally, load your skins-only cfg.
