### ISSUE TITLE
outdated brehhhh

### ISSUE THREAD

**Issue by SteakySteaks** [degeneratehyperbola/NEPS#131]
csgo updated

**Comment by degeneratehyperbola** [comment]
Holy guacamole, 15 days late

**Comment by SteakySteaks** [comment]
respect though bro its crazy how you've been maintaining this cheat for 2 years for no profit

**Comment by degeneratehyperbola** [comment]
My primary focus right now was to find any instability issues. And I didn't find any so far. I have, however, found some features that stopped working. Let me know if NEPS crashes for you.

**Comment by degeneratehyperbola** [comment]
Once again, I did a stress test on some servers with EVERYTHING on and didn't find any crashes so far. Please, feel free to reopen this issue if you find a specific scenario it crashes in
