### ISSUE TITLE
thirdperson is backwards.

### ISSUE THREAD

**Issue by SteakySteaks** [degeneratehyperbola/NEPS#135]
i just loaded my config and thirdperson was looking behind me and i dont know why

**Comment by degeneratehyperbola** [comment]
It is supposed to look on your back

**Comment by SteakySteaks** [comment]
it was looking at my face. i know its supposed to look at my back

**Comment by degeneratehyperbola** [comment]
Wait really? Please, include more information, screenshots, how to reproduce, a config perhaps, I don't have much to work with

**Comment by POWERzzzzz** [comment]
i also have this issue nothing crazy to reproduce you just activate thirdperson i have it bound to my middlemousebutton in this case and the camera is all fucked up not synced to the crosshair at all

also another question while we're at it what does 
![image](https://user-images.githubusercontent.com/24275622/185479285-578461d7-973c-41ed-a046-a55f3c8bd645.png)
DISTANCE: 0u do??

**Comment by degeneratehyperbola** [comment]
@POWERzzzzz 0u means zero units, which in turn means it's turned off

**Comment by degeneratehyperbola** [comment]
Closed due to failure to reproduce
