### ISSUE TITLE
 add KeybindList

### ISSUE THREAD

**Issue by wuuxiehacker303** [degeneratehyperbola/NEPS#136]
I hope add keybindlist to neps
I originally intended to migrate the keybindlist of Osiris and extray，But I failed because the key of Osiris and neps are different，

**Comment by degeneratehyperbola** [comment]
Y'know, I rebuilt the keybind system a little earlier than Osiris did it just for this purpose of creating a keybind state indicator, but found it to be useless as soon as i added AA side indicators. I probably won't add it any time soon, but if you want something in particular to be indicated one way or another, please let me know
