### ISSUE TITLE
Auto-scope issues

### ISSUE THREAD

**Issue by XylylWoofer** [degeneratehyperbola/NEPS#14]
**Describe the bug**
Auto-scope is enabled on all weapons (zooms in on the AUG, unscrews the silencer on the USP-S, changes Glock-18 between auto and burst-fire, despite not being enabled on those weapons in the first place.

**To Reproduce**
1.) Enable aimbot (with an aimkey)
2.) Hold down the aimkey
3.) Witness auto-scope kick in on non-scoped weapons, even with the setting not enabled in those individual weapons.

**Expected behavior**
Shooting guns without auto-scope messing with them.

**Desktop (please complete the following information):**
 - Latest commit, compiled by myself.

**Comment by degeneratehyperbola** [comment]
# Have enabled auto scope on all weapons
![image](https://user-images.githubusercontent.com/65950527/117717259-43e97d00-b1e3-11eb-97f9-8177be678c92.png)
# And disabled it on a specific one
![image](https://user-images.githubusercontent.com/65950527/117717436-7bf0c000-b1e3-11eb-9d84-7ad6f404ba52.png)
# Both set to mouse5
Have been unable to reproduce the behavior. Auto scope works fine for me. It must be a problem on your end, although I have no idea what might cause it...
