### ISSUE TITLE
İs neps virus ?

### ISSUE THREAD

**Issue by DYRREX** [degeneratehyperbola/NEPS#140]
Today I downloaded both the exe version and the dll version of neps which is your cs go cheat. Karspersky named the exe version as VHO:HackTool.Win32.Convagent.gen and deleted it. When I scanned the dll version with virustotal, I got the following output, in short, is it neps virus?
![resim](https://user-images.githubusercontent.com/101344261/188625422-4467f43d-48bb-4b51-858f-0f45bad5678d.png)

**Comment by SteakySteaks** [comment]
nah those are false positives homes

**Comment by DYRREX** [comment]
> 1. NEPS is not virus
> 
>     2. The scans are false postives due to NEPS being a cheat wich means it will get flaged + the exe is injector so another reason for yor Antivirus to delete it
> 
>     3. Its open source, just read thru the code if you want and compile it yourself to be 100% sure
> 
> 
>     * you need to cmpile yourself cuz that dll and exe are old and wont work all you need is here: https://github.com/SK0lll/NEPS/wiki/Guides

I'll try to compile, thanks.
