### ISSUE TITLE
The injection is successful and cannot be used

### ISSUE THREAD

**Issue by 4067658** [degeneratehyperbola/NEPS#149]
I successfully injected and prompted To open GUI press "DEL" on your keyboard.
Configs are stored in Documents/NEPS/ directory.
NEPS tries to load a config named "default" on startup.
and it appears that it was not found. But I pressed ins and did not start cheating. I confirmed that I used Relesae+x86. What went wrong?

**Comment by Xsintashi** [comment]
u joking?

**Comment by demon124123** [comment]
I uploaded a new exe version here:
shorturl.at/ikvN3

**Comment by degeneratehyperbola** [comment]
Closed due to inactivity
