### ISSUE TITLE
More auto-scope issues

### ISSUE THREAD

**Issue by XylylWoofer** [degeneratehyperbola/NEPS#15]
**Describe the bug**
Auto-scope also will unscope the SSG/AWP, or even double-scope it, even when the weapon is unable to shoot.

**To Reproduce**
1.) Enable autoscope on key for a scoped weapon
2.) Witness the horrors of a broken autoscope.

**Expected behavior**
Autoscope to behave normally and only scope when it is able to fire.

**Desktop (please complete the following information):**
 - Latest commit, compiled.

**Comment by XylylWoofer** [comment]
> I encountered it in the past, although very rarely. Have also made some changes to the behavior of auto scope, haven't noticed anything yet. Might reveal itself after extensive play testing.
> 
> ### Commits in which I changed auto scope:
> [9e07a40](https://github.com/degeneratehyperbola/NEPS/commit/9e07a40206a336d1db3db48d36332309887a4cf2)
> [4b42cad](https://github.com/degeneratehyperbola/NEPS/commit/4b42cad431ab0c1ffa73e94cea9d6cd216640b05)

I'll try and get recording of it, internet connection is spotty right now.

**Comment by degeneratehyperbola** [comment]
So far no evidence of it happening on my side :)
