### ISSUE TITLE
[Request] Line of Sight (tracer) like spectator mode

### ISSUE THREAD

**Issue by GioFrandiz** [degeneratehyperbola/NEPS#16]
**_**Is your feature request related to a problem? Please describe.**_**
hi master @degeneratehyperbola  it´s me again, sorry for bothering you but i would like to know if there is any possibility to add this mod to this amazing project

**_**Describe the solution you'd like**_**
It is an option of the spectator mode when watching a replay that helps us to verify in which direction everyone is pointing and it could be activated without problems

**_**Describe alternatives you've considered**_**
Unfortunately I don't know much about coding or reversing (totally noob :(), I think this mod could be a great option and a challenge for this great team and if it is not possible maybe opt for another similar alternative to see where they are aiming at, thank you for this amazing work btw!

**_**Additional context**_**
i´m gonna post some ss

![1](https://user-images.githubusercontent.com/13192759/117846470-78931e00-b24f-11eb-8358-e221f547eda8.png)
![2](https://user-images.githubusercontent.com/13192759/117846496-7e88ff00-b24f-11eb-8d2a-6566dcfef2f6.png)
![3](https://user-images.githubusercontent.com/13192759/117846518-834db300-b24f-11eb-94df-95805351251d.png)
![4](https://user-images.githubusercontent.com/13192759/117846536-88aafd80-b24f-11eb-9a81-d2a6ef0299bc.png)
![5](https://user-images.githubusercontent.com/13192759/117846577-92ccfc00-b24f-11eb-9092-b96f45697fd5.png)
![6](https://user-images.githubusercontent.com/13192759/117846589-96f91980-b24f-11eb-9b27-9779a0bbd39c.png)

**Comment by degeneratehyperbola** [comment]
Thanks for this amazing suggestion!
