### ISSUE TITLE
Project isn't compiling

### ISSUE THREAD

**Issue by ekstazas** [degeneratehyperbola/NEPS#2]
Hello, I'd like to try this out as im fond of Osiris and this should be somewhat similar to it, but whenever I go to build the solution, I get this error:

Error	C2661	'Vector::Vector': no overloaded function takes 3 arguments (compiling source file GameData.cpp)	

Line 671

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xmemory

**Comment by degeneratehyperbola** [comment]
Seems interesting, especially when my code only has 593 lines :/
https://github.com/degeneratehyperbola/NEPS/blob/2487c28f177cd594171f4a67cf222b09691c177f/Hacks/StreamProofESP.cpp#L593

**Comment by ekstazas** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/66647360/112753509-6da66600-8fe0-11eb-8043-6ea4a576b863.png)

**Comment by degeneratehyperbola** [comment]
Do you have all the needed prerequisites in order to compile?
They are:
- Windows SDK ver 10
- DirectX SDK

**Comment by degeneratehyperbola** [comment]
Hello again, I made a simple change where you had a problem a62c8f45963b078a3b19354687eba11c30aa7a8a, try compiling now.
Also to avoid compiling and/or to avoid unstable DLL use the loader I prepackaged with the latest stable release. You can find it in releases tab https://github.com/degeneratehyperbola/NEPS/releases
