### ISSUE TITLE
can't build the dll cheat

### ISSUE THREAD

**Issue by RiskyOnTinder** [degeneratehyperbola/NEPS#22]
Problem 1
**'dummy': const object must be initialized**
---------------------------------------------------
I get an error when trying to build the cheat (  'dummy': const object must be initialized )
I started getting this error since the two last updates. I get this error for lines 1104 and 1250 for Config.cpp
I get an error about the loader too but it is because it was unable to build the dll before.
I would be glad if this could get fixed or if any further help is provided if I am the one doing something wrong :)

p.s. your cheat is really awesome keep the good work up :D
![image](https://user-images.githubusercontent.com/69758103/118353185-d71d0c80-b56d-11eb-9ba1-8779c22d7fd7.png)

Problem 2
I keep getting some crashes when loading into a game
For example, when I load the cheat and just queue for a map I haven't loaded in practice with bots it may just randomly crash when the loading bar reaches the end. A fix for this would be useful too 

*I use this injector : https://github.com/toxa9/CSGOInjector
and i have trying NLoader but it still gets me tha same crashes

**Comment by degeneratehyperbola** [comment]
Hello, thanks for letting me know. I have a question though, are you compiling from the latest commit or latest release's source code? Did you change any project settings and/or retargeted solution to another version of Windows SDK?
Because I, having the latest commit have no problems compiling whatsoever.
![image](https://user-images.githubusercontent.com/65950527/118357585-87494000-b583-11eb-9c1c-2f713bd4eb57.png)
Nevertheless I have a fix for that, and I will push it now.

**Comment by Gaming12846** [comment]
Hello, i also had the dummy problem and solved it by putting {} after dummy (dummy{}). I hope I could help.

**Comment by RiskyOnTinder** [comment]
Hello again, I have the latest stuff and it wouldn't work. I havent changed anything by the way. I dont know how it works but by putting {} after those two errors it is fixed. (lines 1104,1250) 
Thanks for the help. Keep up the good work and I think by putting this curly brackets will solve this issue. I also forgot to mention that previous versions were working fine.
![image](https://user-images.githubusercontent.com/69758103/118389688-a7383c80-b633-11eb-9ecd-72f6e553df74.png)
