### ISSUE TITLE
Can't inject the DLL

### ISSUE THREAD

**Issue by SevenEight123** [degeneratehyperbola/NEPS#3]
Hello, I was looking for a csgo cheat and found this one. I downloaded it and opened in Visual Studio, built a solution and tried to inject the output dll into the game. When I try to do so, I always get an error. I tried different injectors, like Process Hacker, Xenos and Extreme Injector. None of them lets me inject the dll. Visual Studio tells me there are 0 errors, 0 skipped, 1 successful. It's possible that I'm building the project wrong. I just opened the NEPS.vcxproj file and built it. In the folder with dll I always get a folder called db with .obj files there. My dll is 1014KB when I build it as Release and 1640KB when I build it as DebugMin. Please help.

**Comment by degeneratehyperbola** [comment]
Hi, when injecting with Xenos does it show a message box with an error code?
**e.g.**
![image](https://user-images.githubusercontent.com/65950527/112848598-ed036a80-90b0-11eb-8401-a2d460ce0241.png)
Also what settings for injection do you use? Generally it is not that important but there is one thing.
My dll doesn't include any TLS callbacks, that is where many manual ma injectors may fail. If your injector has an option to ignore TLS callbacks, try enabling it and see what it does.
My custom loader injects NEPS without any problems, have you tried it? You can download it in releases tab.

**Comment by SevenEight123** [comment]
Thanks, I tried to inject it with Xenos with the enabled "Ignore TLS" option and it worked! The loader from releases tab also worked perfectly.
