### ISSUE TITLE
Crash on inject

### ISSUE THREAD

**Issue by Ebzdyberybencjusz** [degeneratehyperbola/NEPS#30]
Its crashing every time i try to inject this cheat, ive used like 10 injectors but its always crashing

**Comment by SK0lll** [comment]
make your own or use this one for example (I use this one and it works) [https://github.com/martinjanas/RandoInjector](https://github.com/martinjanas/RandoInjector)

**Comment by SK0lll** [comment]
make sure that you have no missing dependencies or errors during building of the dll.

**Comment by degeneratehyperbola** [comment]
#26
Also, have you tried NLoader, comes bundled with neps?

**Comment by SK0lll** [comment]
> #26
> Also, have you tried NLoader, comes bundled with neps?

I think he did.
Im not 100% shure but I think my game crashed when I tried injecting it with it.


And btw if you get error like missing or cannot find patern 2 or 26 etc.   It might be because of csgo so restart your PC and after that verify the integrity of the game files with steam.

**Comment by degeneratehyperbola** [comment]
Pattern issues were fixed in 71c71343fe64cfaf8b3040166c000e9c1505443e
AIS crashes were fixed in 1dbc2ced11fd80a68a837e13590fe2a7f3145f99
