### ISSUE TITLE
Latest CSGO Update (June 7th, 2021) causes crash.

### ISSUE THREAD

**Issue by XylylWoofer** [degeneratehyperbola/NEPS#34]
**Describe the bug**
Same as in title. Pattern scanning failure.

**To Reproduce**
Just launch CSGO and inject NEPS, compiled on latest commit or from release, you crash due to pattern scanning failure.

**Expected behavior**
The cheat injects

**Screenshots**
![image](https://user-images.githubusercontent.com/83837190/121131962-86ac6e00-c7fe-11eb-943b-80341e4c9a4c.png)
![image](https://user-images.githubusercontent.com/83837190/121131977-8dd37c00-c7fe-11eb-8e6b-6d145fc095be.png)
![image](https://user-images.githubusercontent.com/83837190/121131989-91670300-c7fe-11eb-95d3-0532582e225c.png)
![image](https://user-images.githubusercontent.com/83837190/121132026-9af06b00-c7fe-11eb-924a-26ce5b1b2c66.png)

**Desktop (please complete the following information):**
 - NEPS 1.2.1

**Comment by Rainerr123** [comment]
having same issue :)
