### ISSUE TITLE
Nothing shows up when I press DEL

### ISSUE THREAD

**Issue by Leozin-777** [degeneratehyperbola/NEPS#37]
I already disabled my av and windows defender, it just shows the menu but without anything on it, and sometimes don´t even show up the menu

**Comment by degeneratehyperbola** [comment]
I am gonna ask you to provide screenshots, NEPS version, OS name and version, system specs (particularly GPU and CPU) reproduction instructions (if any) and the environment in which the bug happened (e.g. any other cheat loaded, injector used, vac byass). According to what you wrote, I was unable to reproduce the bug nor I have any idea what is this issue about.
