### ISSUE TITLE
Lag for no reason!

### ISSUE THREAD

**Issue by alexezz21** [degeneratehyperbola/NEPS#39]
**Describe the bug**

**To Reproduce**
1. Inject cheat with NLoader
2. Load a config and go into a match
3. It will lag for no reason

Please fix it!

**Comment by alexezz21** [comment]
But if i go into a workshop map it wont lag!

**Comment by mxez** [comment]
try to adding bots on yout local server with workshop map, if it will start lagging then problem is in your computer

**Comment by alexezz21** [comment]
It only happens with NEPS. Tried what you said and it was the same :/

**Comment by wuuxiehacker303** [comment]
I also encountered the situation of lag for no reason，Even if I turn off all neps functions，There is also a lag

**Comment by degeneratehyperbola** [comment]
Try to recompile with other enhanced instruction sets like AVX or AVX2
