### ISSUE TITLE
Aimbot circles

### ISSUE THREAD

**Issue by ignhedgy** [degeneratehyperbola/NEPS#4]
Whenever aimbot is enabled, and is shooting, circles appear on all parts of the enemy player. Even tho i could not find a visual or esp setting like that. How do i get rid of it? It is very annoying.

**Comment by degeneratehyperbola** [comment]
Those circles are displaying all the possible targeting points and is a feature for debugging. You must've compiled with "DebugMin" configuration. To get rid of them recompile NEPS for release or use a prepackaged loader (which is actually recommended as it has the most stable version) https://github.com/degeneratehyperbola/NEPS/releases/tag/1.0
