### ISSUE TITLE
Failed to find pattern #24

### ISSUE THREAD

**Issue by danielfan61a** [degeneratehyperbola/NEPS#41]
![image](https://user-images.githubusercontent.com/86361358/124828769-9c34c500-df6f-11eb-8db3-fe615a50f6e6.png)
Pattern update is needed.

**Comment by danielfan61a** [comment]
causes crashes.

**Comment by 1274936135** [comment]
+1

**Comment by SK0lll** [comment]
+1

**Comment by degeneratehyperbola** [comment]
Fixed in d10cfdb220e4ed15dd452f19219e5d1c64fd1a6a

**Comment by danielfan61a** [comment]
thank you very much
