### ISSUE TITLE
the about menu crashes the game

### ISSUE THREAD

**Issue by danielfan61a** [degeneratehyperbola/NEPS#42]
clicking anything on the about menu, discord, github crashes the game fix pls
![image](https://user-images.githubusercontent.com/86361358/125139794-19477200-e109-11eb-801b-9c3d187e9fdc.png)

**Comment by degeneratehyperbola** [comment]
Apparently `ShellExecute` crashes for you, it is supposed to automatically open corresponding links in your default browser, do you have it set? I am afraid the only method valid is the one I use, at least of which I am aware of, so currently nothing that I cam do. Feel free to reopen thos issue if you fing a way.

**Comment by danielfan61a** [comment]
yes i do have chromium browser set as default
