### ISSUE TITLE
When I inject neps, the game will crash

### ISSUE THREAD

**Issue by wuuxiehacker303** [degeneratehyperbola/NEPS#43]
**Describe the bug**
When neps is injected, the game will crash

**To Reproduce**
1. Go to 'Open NLoader'
2. Click on 'Start the game'
3. Crash in the game
4. Crash

**Expected behavior**
After a while, the game broke down

**Screenshots**

**Desktop (please complete the following information):**
 - Version of NEPS [e.g. 1.3]

**Comment by degeneratehyperbola** [comment]
Do you have config named "default"? If so try to rename it to something else and try again

**Comment by wuuxiehacker303** [comment]
> 你有名为"默认"的配置吗？如果是这样，请尝试将其重命名为其他内容并重试

I don't have ’default‘ config，Even if I don't use any configs，It's still crash，And tell me ‘faild to find pattern #24'

**Comment by degeneratehyperbola** [comment]
I have already fixed this bug in d10cfdb220e4ed15dd452f19219e5d1c64fd1a6a although I haven't yet released this version

**Comment by wuuxiehacker303** [comment]
> 我已经修复了这个错误在[d10cfdb](https://github.com/degeneratehyperbola/NEPS/commit/d10cfdb220e4ed15dd452f19219e5d1c64fd1a6a)虽然我还没有发布此版本。在一段时间内，我将发布固定版本

Thank you
