### ISSUE TITLE
1.3.1 Hotfix Crash

### ISSUE THREAD

**Issue by advance24th** [degeneratehyperbola/NEPS#62]
This is **Short and simple**, but hotfix version 1.3.1 your latest release crashes my game about 3 minutes into a game.
**iv used** your injector, a private undetected injector, and a public private injector, all **work with no avail to the crash**.

Im pretty sure this is something with the cheat itself.
i hope it can be fixed, because i really like this cheat.

**UPDATE!**
your cheat now just fully crashes when im in the loading screen to a game. due to the new csgo update Riptide.
Your most vital cheat does not work currently. can you fix it soon?

**Comment by Spamm00r** [comment]
#metoo

**Comment by advance24th** [comment]
This is everyone Spamm00r, most updates break cheats for a few days. Its up the developer to fix it

**Comment by degeneratehyperbola** [comment]
I fixed some crashes in a941f96ec0a19ca0b90900337f076f0e1ab1d61e however I'm not sure if I encountered any map load crashes so far. Let me know if it still crashes and if you are able to reproduce the crash consistently

**Comment by advance24th** [comment]
Ok ill look into it

**Comment by advance24th** [comment]
thank you! this version offically works with csgo's riptide update! your the best keep on doing your thing with this cheat
