### ISSUE TITLE
Better Resolver and Anti aim

### ISSUE THREAD

**Issue by AutismWarrior** [degeneratehyperbola/NEPS#68]
I don't like how the 'LBY Resolver' doesn't really resolve anything, prediction is non existent.

I would like any resolver that atleast tries to shoot and predict.

You can pull a resolver from any other cheat that is relatively decent.

I know this cheat isn't meant for hvh, but if it has the options for it, atleast have them in working order.

I also suggest working desync.

Edit: An animlayer resolver should work still, correct me if I'm wrong.

**Comment by somberx** [comment]
I think this would make  it a much more viable semi rage cheat if options were added like this :) working legit aa+deysnc, a half decent resolver, making one isnt to difficult for it to resolve basic shit this would be cool to see added :)

**Comment by degeneratehyperbola** [comment]
Closing as these features, slowly but steadily, are getting added and improved. In fact, the only thing left to do is improvement
