### ISSUE TITLE
Cheat could be outdated

### ISSUE THREAD

**Issue by KakashiSeno** [degeneratehyperbola/NEPS#69]
The cheat loads fine but wehen im entering a map it crashes and closes itself.

**Comment by KakashiSeno** [comment]
I downloaded it and just wantet to go on a test server but it crashes. I changed nothing. only inject witout config.

**Comment by degeneratehyperbola** [comment]
Ok, so I've been testing Neps for a past day and haven't found any issues with it. However, there are known issues with the skinchanger as I said before. Skinchanger's invalid instruction crash can be triggered through loading configs with skins and/or interacting with skinchanger's UI. I wonder if it produces any injection issues

**Comment by degeneratehyperbola** [comment]
I am going to test a machine with an older CPU with NEPS. Perhaps it is indeed caused by something compiler related

**Comment by KakashiSeno** [comment]
i can give u my specs realy quick. i9 9980hk (2.4 to 5.1 ghz 8 core 16 threads)  16gig ram Nvidia rtz 2080 max q design winver 21H1 Build 19042,1288 all drivers are up too date. it only crashes if i join a server.

**Comment by degeneratehyperbola** [comment]
> it only crashes if i join a server
In this commit 6d9ea384c572a9e9ae828b7f289ddaafdbeb558a I have fixed one crash related to that, if nothing changed since I will need to search for an apparent issue
