### ISSUE TITLE
a few ideas

### ISSUE THREAD

**Issue by ignhedgy** [degeneratehyperbola/NEPS#7]
1, Have you considered adding a script/lua system? it would be a huge thing to add, since people can add/improve features
2, i know the resolver is experimental , and i tried screwing around wtih the delta, but it still misses most the time. So improving that might be good (or adding options to it..?)
3, Maybe a better desync? don't get me wrong it is working, but the fake angle barely leaves my real angle, making it almost pointless in mm.

**Comment by degeneratehyperbola** [comment]
1.Yes, it is on planned features list definitely. The list itself is not yet public as it is incomplete. I was thinking about adding python support, actually.
2.Yeah that is true. This resolver randomly chooses a right delta out of 3 premade (-60deg, 0deg, 60deg) as (max desync left, no desync, max desync right). This gives it 33.3% chance to resolve the target. I have looked on other possible implementations, and i have chosen one from "neverlose" 2nd resolver, whose source code is "partly" public. *in form of gs/aw luas
3.Welp, can't help with that, unfortunately. You will achieve the maximum possible desync close to 120deg (which I believe is max desync in CS:GO) with these settings:
![image](https://user-images.githubusercontent.com/65950527/115005231-51e00280-9eb0-11eb-8498-51c50b06a17e.png)
with fake up (only on community servers as this gets you insta-overwatch):

<p float="left">

<img src="https://user-images.githubusercontent.com/65950527/115005358-73d98500-9eb0-11eb-83dc-c5fd3666a63b.png" height="200" />

<img src="https://user-images.githubusercontent.com/65950527/115005567-aa170480-9eb0-11eb-94df-0eff7095ef14.png" height="200" />

</p>

or perhaps with dual barettas and pitch 0:
![image](https://user-images.githubusercontent.com/65950527/115006362-74bee680-9eb1-11eb-806b-5a1387e2a352.png)

**Comment by ignhedgy** [comment]
Alright, thanks for answering, I'm currently trying out the antiaim settings. For now I might just paste another cheats resolver until it's fixed, or just not use a resolver at all.
