### ISSUE TITLE
Crashing after new commit (c3caf6c)

### ISSUE THREAD

**Issue by hedgyx** [degeneratehyperbola/NEPS#75]
**Describe the bug**
The game crashes after "Receiving Data..", using latest version, compiled with x86-release settings.

**To Reproduce**
download c3caf6c-commit
compile the cheat with x86-release settings.
inject the cheat with the latest neps loader
the game immediately crashes after the loading screen gets to "Receiving Game Data.."

**Expected behavior**
It should normally start

**Screenshots**
https://streamable.com/mpmn75

**Desktop (please complete the following information):**
 - Version of NEPS c3caf6c-commit

**Comment by dctrlight** [comment]
+

**Comment by degeneratehyperbola** [comment]
Fixed in 0bc6686fcfe27184133853249083ca972aa712eb
