### ISSUE TITLE
Why is the aim from this hack so worse than Osiris?

### ISSUE THREAD

**Issue by diekunstderfuge** [degeneratehyperbola/NEPS#77]
Isn't this hack based on Osiris? But this aim Is so much worse.

The only advantage is the autowall. But even that is bad, since the aim is not good.

Why don't you use the aimbot from Osiris instead, since it's better?

**Comment by ThebestkillerTBK** [comment]
Its working fine, the same quality as Osiris

**Comment by degeneratehyperbola** [comment]
Well, I don't know about You but I manage to go against some ragers with NEPS
