### ISSUE TITLE
pattern #12 and #17 error

### ISSUE THREAD

**Issue by Koibeta** [degeneratehyperbola/NEPS#80]
Hi i believe that csgo just updated on the 10th of December so im not sure if its the update that is causing this error (failed to find pattern #12 and #17), but if it has nothing to do with the update then could someone suggest to me how to fix it please ;) it would be greatly appriciated. I have tried to delete all files related to osiris and recompiled it again, but it didn't work and I have tried to verify the integrity of the files and the error still appears.

**Comment by ThebestkillerTBK** [comment]
`invertoryBlock = MemorySearch::findPattern("client", "\x84\xC0\x75\x04\xB0\x01\x5E");`

`clearHudWeapon = relativeToAbsolute<decltype(clearHudWeapon)>(MemorySearch::findPattern("client", "\xE8????\x8B\xF0\xC6\x44\x24??\xC6\x44\x24") + 1);`
