### ISSUE TITLE
Game crashes whenever the bomb explodes

### ISSUE THREAD

**Issue by hedgyx** [degeneratehyperbola/NEPS#88]
**Describe the bug**
The game crashes whenever the bomb explodes

**To Reproduce**
1. Get in a match
2. Wait for the bomb to explode
3. Crash
**Desktop (please complete the following information):**
 - Version of NEPS c0442f0 compiled in visual studio 2019 release x86, injected with latest csghost

**Additional context**
I even tried to turn off the bomb timer, and resetting the whole config, but it still crashes.
I tried using osiris, and surprisingly it didn't crash with similar visuals (visible only glow chams, and a basic esp)

**Comment by degeneratehyperbola** [comment]
Fixed in 07c4db04d8dd1221cea93da85d92f82eb2552edb
