### ISSUE TITLE
The skinchanger are acting wierd

### ISSUE THREAD

**Issue by AliasPerry** [degeneratehyperbola/NEPS#9]
The skin changer works sometimes for me, and stickers are completely broken I might fix this if someone hasn't already but that's it , and the aimbot feels smooth af.

**Comment by degeneratehyperbola** [comment]
Skinchanger fixed in 38cc324f85f5fb8c8942b6e3d27f8d854caeb328
As for aimbot, make sure interpolation is turned off and aimstep set to 255. If it was just a complement, then sorry, misunderstood you, and thanks.

**Comment by AliasPerry** [comment]
was a complement, got it working thanks
